# Generated by Django 4.2.5 on 2023-10-26 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_y_apellido', models.CharField(max_length=250, verbose_name='Nombre y apellido')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('telefono', models.IntegerField(max_length=250, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=250, verbose_name='Email')),
                ('tipo_de_consulta', models.IntegerField(choices=[('', '-Seleccione-'), (1, 'Soporte'), (2, 'Consultas sobre peliculas o series'), (3, 'Trabajar en DJflix')], verbose_name='Tipo de consulta')),
                ('mensaje', models.TextField(max_length=500, verbose_name='Mensaje')),
                ('fecha_y_hora', models.DateField(null=True, verbose_name='Fecha y hora')),
                ('se_envio_email', models.BooleanField(default=False, verbose_name='se_envio_email')),
            ],
        ),
    ]
