# Generated by Django 4.2.5 on 2023-10-26 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_contacto_fecha_y_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='telefono',
            field=models.IntegerField(verbose_name='Teléfono'),
        ),
    ]
