# Generated by Django 4.2.2 on 2023-10-20 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capitulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capitulo_numero', models.IntegerField(null=True, verbose_name='Capitulo Número')),
                ('nombre_capitulo', models.CharField(max_length=200, verbose_name='Nombre del Capitulo')),
                ('descripcion', models.TextField(max_length=500, verbose_name='Descripcion')),
                ('portada', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Portada')),
                ('duracion', models.DateTimeField(verbose_name='Duracion')),
                ('enlace', models.TextField(max_length=500, verbose_name='Enlace')),
                ('baja', models.DateField(verbose_name='baja')),
            ],
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Peliculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre Pelicula')),
                ('fecha_estreno', models.DateField(verbose_name='Fecha de estreno')),
                ('descripcion', models.TextField(max_length=500, verbose_name='Descripcion')),
                ('portada', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Portada')),
                ('duracion', models.DateTimeField(verbose_name='Duracion')),
                ('clasificacion', models.CharField(max_length=250, verbose_name='Clasificacion')),
                ('enlace', models.TextField(max_length=500, verbose_name='Enlace')),
                ('baja', models.DateField(verbose_name='baja')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.categorias')),
            ],
        ),
        migrations.CreateModel(
            name='Suscriptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_apellido', models.CharField(max_length=500, verbose_name='Nombre y Apellido')),
                ('direccion', models.CharField(max_length=700, verbose_name='Direccion')),
                ('dni', models.IntegerField(verbose_name='DNI')),
                ('email', models.EmailField(max_length=250, verbose_name='Email')),
                ('pais', models.CharField(max_length=200, verbose_name='Pais')),
                ('ciudad', models.CharField(max_length=200, verbose_name='Ciudad')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('tipo_plan', models.CharField(max_length=200, verbose_name='plan')),
                ('baja', models.DateField(default=False, verbose_name='baja')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Visualizaciones_peliculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de vista')),
                ('tiempo_visto', models.DurationField(verbose_name='Tiempo visto')),
                ('id_pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.peliculas')),
                ('id_suscriptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.suscriptor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Visualizaciones_capitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de vista')),
                ('tiempo_visto', models.DurationField(verbose_name='Tiempo visto')),
                ('id_capitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.capitulos')),
                ('id_suscriptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.suscriptor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='capitulos',
            name='id_pelicula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.peliculas'),
        ),
    ]
