# Generated by Django 4.2.2 on 2023-10-18 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_plan', models.CharField(max_length=150, verbose_name='Tipo de Plan')),
                ('baja', models.DateField(verbose_name='baja')),
            ],
        ),
        migrations.CreateModel(
            name='Suscriptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_apellido', models.CharField(max_length=500, verbose_name='Nombre y Apellido')),
                ('direccion', models.CharField(max_length=700, verbose_name='Direccion')),
                ('dni', models.TextField(max_length=350, verbose_name='DNI')),
                ('email', models.EmailField(max_length=250, verbose_name='Email')),
                ('pais', models.CharField(max_length=200, verbose_name='Pais')),
                ('ciudad', models.CharField(max_length=200, verbose_name='Ciudad')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('tipo_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.suscripcion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Visualizaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pelicula', models.IntegerField(verbose_name='Id Pelicula')),
                ('fecha', models.DateField(verbose_name='Fecha de vista')),
                ('tiempo_visto', models.DurationField(verbose_name='Tiempo visto')),
                ('id_suscriptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.suscriptor')),
            ],
        ),
        migrations.CreateModel(
            name='Peliculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre Pelicula')),
                ('fecha_estreno', models.DateField(verbose_name='Fecha de estreno')),
                ('descripcion', models.TextField(max_length=500, verbose_name='Descripcion')),
                ('portada', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Portada')),
                ('duracion', models.DateTimeField(verbose_name='Duracion')),
                ('clasificacion', models.CharField(max_length=250, verbose_name='Clasificacion')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.categorias')),
                ('suscriptor', models.ManyToManyField(to='administracion.suscriptor')),
            ],
        ),
    ]
