# Generated by Django 4.2.2 on 2023-10-26 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(max_length=500, verbose_name='Descripcion')),
                ('portada', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Portada')),
                ('enlace', models.TextField(max_length=500, verbose_name='Enlace')),
                ('baja', models.DateField(null=True, verbose_name='baja')),
                ('numero_capitulo', models.IntegerField(verbose_name='Número de Capitulo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=100, verbose_name='Nombre categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(max_length=500, verbose_name='Descripcion')),
                ('portada', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Portada')),
                ('enlace', models.TextField(max_length=500, verbose_name='Enlace')),
                ('baja', models.DateField(null=True, verbose_name='baja')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.categorias')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Suscriptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_apellido', models.CharField(max_length=500, verbose_name='Nombre y Apellido')),
                ('dni', models.IntegerField(verbose_name='DNI')),
                ('email', models.EmailField(max_length=250, verbose_name='Email')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('baja', models.DateField(null=True, verbose_name='baja')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Visualizaciones_pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de vista')),
                ('tiempo_visto', models.DurationField(verbose_name='Tiempo visto')),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.pelicula')),
                ('suscriptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.suscriptor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Visualizaciones_capitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de vista')),
                ('tiempo_visto', models.DurationField(verbose_name='Tiempo visto')),
                ('capitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.capitulo')),
                ('suscriptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.suscriptor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(max_length=500, verbose_name='Descripcion')),
                ('portada', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Portada')),
                ('enlace', models.TextField(max_length=500, verbose_name='Enlace')),
                ('baja', models.DateField(null=True, verbose_name='baja')),
                ('cant_capitulos', models.IntegerField(verbose_name='Cantidad de capítulos')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.categorias')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='pelicula',
            name='suscriptor',
            field=models.ManyToManyField(through='administracion.Visualizaciones_pelicula', to='administracion.suscriptor'),
        ),
        migrations.AddField(
            model_name='capitulo',
            name='serie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.serie'),
        ),
        migrations.AddField(
            model_name='capitulo',
            name='suscriptor',
            field=models.ManyToManyField(through='administracion.Visualizaciones_capitulo', to='administracion.suscriptor'),
        ),
    ]
