<<<<<<< HEAD
# Generated by Django 4.2.2 on 2023-10-29 23:35
=======
# Generated by Django 4.2.5 on 2023-10-29 23:15
>>>>>>> 6075857f194edc3e2d4862b0f63b3bb132b08415

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='cant_capitulos',
            field=models.IntegerField(null=True, verbose_name='Cantidad de capítulos'),
        ),
    ]
