# Generated by Django 4.2.2 on 2023-10-29 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='cant_capitulos',
            field=models.IntegerField(null=True, verbose_name='Cantidad de capítulos'),
        ),
    ]
