# Generated by Django 4.2.5 on 2023-10-26 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_contacto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacto',
        ),
    ]
