<<<<<<< HEAD
# Generated by Django 4.2.5 on 2023-11-02 21:55
=======
# Generated by Django 4.2.2 on 2023-11-01 23:45
>>>>>>> fd0160b32ed2aacdb337924905747da61e6c957e

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_alter_serie_cant_capitulos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suscriptor',
            options={'verbose_name_plural': 'Suscriptores'},
        ),
    ]
