# Generated by Django 4.2.2 on 2023-11-01 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_alter_serie_cant_capitulos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suscriptor',
            options={'verbose_name_plural': 'Suscriptores'},
        ),
    ]
