# Generated by Django 4.2.5 on 2023-11-02 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_alter_suscriptor_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='categoria',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='categoria',
            field=models.ManyToManyField(to='administracion.categorias'),
        ),
        migrations.AddField(
            model_name='serie',
            name='categoria',
            field=models.ManyToManyField(to='administracion.categorias'),
        ),
    ]
