# Generated by Django 4.2.2 on 2023-11-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_alter_suscriptor_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitulo',
            name='enlace',
            field=models.URLField(verbose_name='Enlace'),
        ),
        migrations.AlterField(
            model_name='capitulo',
            name='portada',
            field=models.URLField(null=True, verbose_name='Portada'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='enlace',
            field=models.URLField(verbose_name='Enlace'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='portada',
            field=models.URLField(null=True, verbose_name='Portada'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='enlace',
            field=models.URLField(verbose_name='Enlace'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='portada',
            field=models.URLField(null=True, verbose_name='Portada'),
        ),
    ]
