# Generated by Django 4.2.2 on 2023-11-02 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0006_alter_capitulo_portada_alter_pelicula_portada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitulo',
            name='portada',
            field=models.ImageField(null=True, upload_to='peliculas/', verbose_name='Portada'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='portada',
            field=models.ImageField(null=True, upload_to='peliculas/', verbose_name='Portada'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='portada',
            field=models.ImageField(null=True, upload_to='peliculas/', verbose_name='Portada'),
        ),
    ]
