# Generated by Django 4.2.2 on 2023-11-04 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_remove_pelicula_categoria_remove_serie_categoria_and_more'),
        ('administracion', '0007_alter_capitulo_portada_alter_pelicula_portada_and_more'),
    ]

    operations = [
    ]
