# Generated by Django 4.2.2 on 2023-11-04 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0008_merge_20231103_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitulo',
            name='enlace',
            field=models.TextField(max_length=500, verbose_name='Enlace'),
        ),
        migrations.AlterField(
            model_name='capitulo',
            name='portada',
            field=models.ImageField(null=True, upload_to='imagenes/', verbose_name='Portada'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='enlace',
            field=models.TextField(max_length=500, verbose_name='Enlace'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='portada',
            field=models.ImageField(null=True, upload_to='imagenes/', verbose_name='Portada'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='enlace',
            field=models.TextField(max_length=500, verbose_name='Enlace'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='portada',
            field=models.ImageField(null=True, upload_to='imagenes/', verbose_name='Portada'),
        ),
    ]
