# Generated by Django 4.2.5 on 2023-11-04 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0009_alter_capitulo_enlace_alter_capitulo_portada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='categoria',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administracion.categorias'),
        ),
        migrations.AddField(
            model_name='serie',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administracion.categorias'),
        ),
    ]
