# Generated by Django 4.2.2 on 2023-11-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0011_suscriptor_password1_suscriptor_password2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorias',
            options={'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterField(
            model_name='categorias',
            name='nombre_categoria',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre categoria'),
        ),
        migrations.AlterField(
            model_name='suscriptor',
            name='password1',
            field=models.CharField(default=1234, max_length=16, verbose_name='password1'),
        ),
        migrations.AlterField(
            model_name='suscriptor',
            name='password2',
            field=models.CharField(default=1234, max_length=16, verbose_name='password2'),
        ),
        migrations.AlterField(
            model_name='suscriptor',
            name='username',
            field=models.CharField(default='suscriptor', max_length=16, verbose_name='username'),
        ),
    ]
