# Generated by Django 4.2.2 on 2023-11-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0012_alter_categorias_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscriptor',
            name='password1',
            field=models.CharField(default='suscriptor', max_length=16, verbose_name='password1'),
        ),
        migrations.AlterField(
            model_name='suscriptor',
            name='password2',
            field=models.CharField(default='suscriptor', max_length=16, verbose_name='password2'),
        ),
    ]
